application:
  topic: test_topic
spring:
  kafka:
    consumer:
      bootstrap-servers: "[::1]:9092"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: earliest
      group-id: consumers-group
    producer:
      bootstrap-servers: "[::1]:9092"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    org:
      springframework: debug
      springframework.kafka: debug